### ISSUE TITLE
✨ 11월 스터디 일지

### ISSUE THREAD

**Issue by devpla** [algo-itzy/algo-itzy#115]
# 11월 스터디 계획

### 스터디명
알고있지! (Algo-Itzy)

<br />

### 진행
- 주 2회 2시간 진행 (목요일 20시, 일요일 12시)
- 스터디 전 까지 해당 문제 풀이 및 PR
- 다른 사람들의 PR 확인 후 코드 리뷰 (질문, 칭찬, 개선안) 
- 게더타운에서 코드 리뷰 진행
  - 본인 PR에 달린 코드 리뷰를 참고해 코드 설명 및 질의응답
  - 도출 과정(Ideation)에 집중하여 리뷰 (필요 시 시각적 자료 준비)
  - 서로 적극적인 피드백 공유 (좋은 점, 개선안, 리팩토링)
- 스터디가 끝나면 다음에 풀 주제 및 문제 선정

<br />

### 규칙
- 코드 스타일 및 커밋 컨벤션 준수
- PR을 통한 코드 리뷰
  - master에 직접 커밋 X
  - 최소 두 명 이상이 승인을 받은 뒤 merge
- 벌금 제도를 통해 스터디 참여를 독려 (사용처: 코로나 안정 시 오프라인 회식🍽)

<br />

### 특이사항
- 현업의 코드 리뷰 및 협업 방식 활용. 지속적으로 개선 예정
- 업무 자동화 (디렉토리 생성 등 반복적인 작업)

**Comment by devpla** [comment]
# 211104
![image](https://user-images.githubusercontent.com/87457066/140314623-09b52985-2519-4228-b583-2dd1c49707e0.png)

![image](https://user-images.githubusercontent.com/87457066/140314560-597cc91b-6f06-4936-b672-c3ef3794dbf5.png)
![image](https://user-images.githubusercontent.com/87457066/140314578-d36e3548-ee94-4ad5-8e1a-e920e398e7ca.png)

**Comment by seokzin** [comment]
### 211107
![image](https://user-images.githubusercontent.com/43740455/140630993-f696a7e6-6c1b-47a1-ab52-d9f095b783a1.png)

**Comment by devpla** [comment]
![image](https://user-images.githubusercontent.com/87457066/141668650-a7e3f99c-60f3-44c0-8f44-b60f6527e620.png)

![image](https://user-images.githubusercontent.com/87457066/141668646-767b7f67-f806-4539-89fc-ccf10a274937.png)

**Comment by devpla** [comment]
![image](https://user-images.githubusercontent.com/87457066/142405082-5640e84d-1514-4e6c-84fe-42a8af2c6509.png)
![image](https://user-images.githubusercontent.com/87457066/142405169-b529e047-5d50-4de9-b662-97025eb34a28.png)

**Comment by devpla** [comment]
![image](https://user-images.githubusercontent.com/87457066/142747779-f6fe4fa2-46c7-4171-81df-fcc1bf882e17.png)

**Comment by devpla** [comment]
11/25 스터디는 쉼
