### ISSUE TITLE
✨ 10월 스터디 일지

### ISSUE THREAD

**Issue by devpla** [algo-itzy/algo-itzy#57]
# 10월 스터디 계획

- **스터디명**: 알고있지! (Algo-Itzy)

- **진행**: 주 2회(목요일 20시, 일요일 12시 / 2시간)
   - 스터디 전까지 해당 회차의 알고리즘 문제 풀이 및 깃허브 업로드
   - 개인 별 Pull Requests 작성
      - 스터디 전에 다른 사람들의 PR 확인하고 리뷰(질문, 칭찬, 개선안) 남기기

   - 디스코드에서 코드 리뷰 진행
      - PR 리뷰를 참고해 본인의 코드 설명, 질의응답
      - 코드 결과보다는 도출 과정에 집중하여 리뷰합니다. 필요 시 시각적 자료를 준비합니다.
      - 좋은 점, 개선할 점 등 적극적인 피드백 공유

   - 모든 리뷰가 끝나면 다음에 풀 문제 선정

- **규칙**
   - 깃허브 업로드 시 코드 및 커밋 컨벤션을 지킵니다.
   - PR, 코드리뷰 기능을 활용합니다.
      - 개인 별 브랜치에서 개인 코드 관리 (master 브랜치에는 커밋하지 않습니다.)
      - PR은 두 명 이상이 승인 시 merge합니다.

   - 스터디 참여 독려를 위해 벌금 제도를 운영합니다. (사용처: 코로나 잠잠해지면 오프라인 회식🍽)

- **특이사항**
  - 현업의 코드 리뷰 및 협업 방식 활용. 지속적으로 개선 예정
   - 디렉토리 생성 등 반복적인 작업은 파이썬을 활용하여 업무 자동화

**Comment by seokzin** [comment]
## 2021-10-03

### 📋 스터디 내용

![image](https://user-images.githubusercontent.com/87457066/135461633-5ca8ceff-7e67-4083-b6be-0a14ca2e4c92.png)

### 📌 특이사항
- 알고리즘 심화 과정 후, 문제 비중을 줄이고 자료구조, CS 비중 늘릴 계획 (임시)

### 📢 다음 스터디 안내
#### 10월 7일 스터디 과제

![image](https://user-images.githubusercontent.com/43740455/135739454-1224c95e-cb10-4846-b78a-8c0f0dc1a2dd.png)

**Comment by devpla** [comment]
## 2021-10-07

### 📋 스터디 내용

![image](https://user-images.githubusercontent.com/87457066/136377025-7beb5dae-488e-4741-8eab-98a1bea73e3e.png)

### 📌 특이사항
- CS 도입 차차 생각하기

### 📢 다음 스터디 안내
#### 10월 10일 스터디 과제
![image](https://user-images.githubusercontent.com/87457066/136377998-3bebc35a-d691-445c-a25e-e3b75c9a9a75.png)

**Comment by devpla** [comment]
## 2021-10-10

![image](https://user-images.githubusercontent.com/87457066/136682755-35e76fb0-1508-4a07-bfb5-61593cd09e12.png)

### 📋 스터디 내용
![image](https://user-images.githubusercontent.com/87457066/136682761-2842ebbb-5d0e-410b-a2a2-620e53882822.png)

### 📌 특이사항
- CS 도입

### 📢 다음 스터디 안내
#### 10월 11일 스터디 과제
![image](https://user-images.githubusercontent.com/87457066/136682830-2691a96f-138b-42ea-b605-e5ca1eea1bed.png)

**Comment by devpla** [comment]
## 다음 스터디 안내
![image](https://user-images.githubusercontent.com/87457066/137611460-f4e3652b-9da4-4d3b-8b65-17425e6f4305.png)

**Comment by seokzin** [comment]
### 10/31
- 사진 X

### 11/4 스터디 안내
![image](https://user-images.githubusercontent.com/43740455/139613646-8ada436e-4594-4ff0-8426-f94e0a014594.png)

![image](https://user-images.githubusercontent.com/43740455/139613679-ccb43748-3386-489b-a3cc-2543037d7951.png)
